// examples/demo-app-svelte/src/DemoHeader.svelte
<script lang="ts">
  let { active }: { active: "vue" | "react" | "preact" | "svelte" } = $props();
</script>

<header class="demo-header">
  <nav>
    <a href="/" class={active === "vue" ? "active" : undefined}>Vue</a>
    <a href="/react-demo/" class={active === "react" ? "active" : undefined}>
      React
    </a>
    <a href="/preact-demo/" class={active === "preact" ? "active" : undefined}>
      Preact
    </a>
    <a href="/svelte-demo/" class={active === "svelte" ? "active" : undefined}>
      Svelte
    </a>
  </nav>
</header>

// examples/demo-app-react/src/DemoHeader.tsx
export default function DemoHeader({ active }: { active: "vue" | "react" }) {
  return (
    <header className="demo-header">
      <nav>
        <a href="/" className={active === "vue" ? "active" : undefined}>
          Vue
        </a>
        <a
          href="/react-demo/"
          className={active === "react" ? "active" : undefined}
        >
          React
        </a>
      </nav>
    </header>
  );
}
